name: Upload release assets
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The git tag'
        required: true
      workflow_url:
        description: 'The workflow URL'
        required: true
jobs:
  upload:
    runs-on: ubuntu-16.04
    steps:
      - run: gh api ${{ github.event.inputs.workflow_url }}
