name: Upload release assets
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The git tag'
        required: true
      workflow_url:
        description: 'The workflow URL'
        required: true
jobs:
  upload:
    runs-on: ubuntu-16.04
    steps:
      - run: |
          gh api ${{ github.event.inputs.workflow_url }}/artifacts | jq -r '.artifacts[].archive_download_url' | while read url; do
            gh api $url >> archive.zip
            unzip archive.zip
          done

          assets=$(gh api repos/wojtekmach/otp_releases/releases/$(gh api repos/wojtekmach/otp_releases/releases/tags/${{ github.event.inputs.tag }} | jq .id)/assets | jq -r '.[].name')

          for i in *.tar.gz; do
            if echo assets | grep $i; then
              echo $i already uploaded
            else
              gh release upload -R wojtekmach/otp_releases ${{ github.event.inputs.tag }} $i
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
